import Head from "next/head";
import React from "react";

const Header = ({title = "Dynamic test proj"} : {title?: string}) => {
  return (
    <Head>
      <meta charSet="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="manifest" href="%PUBLIC_URL%/manifest.json" /> */}
      <title>Ryan Favour — Transforming designs into reality</title>
      <meta
        name="title"
        content="Ryan Favour — Transforming designs into reality"
      />
      <link rel="icon" href="/favicon.ico" />
      <title>{title}</title>
    </Head>
  );
};

export default Header;
